#!/usr/bin/env bash
# One-shot Coturn setup for the Oracle Cloud Always Free VM.
# Run from the repo root on the VPS:  bash deployment/coturn/setup.sh
#
# What it does:
#   1. Detects the public + private IP of this VM
#   2. Fills them into deployment/coturn/coturn.conf (external-ip)
#   3. Generates a random TURN password (or reuse $TURN_PASSWORD)
#   4. Writes deployment/coturn/turnuserdb.conf with the turnadmin key
#   5. Starts the container with docker compose
#   6. Prints the exact Render env vars to paste into the dashboard
set -euo pipefail

cd "$(dirname "$0")/.."   # now inside deployment/

PUBLIC_IP="${PUBLIC_IP:-$(curl -4 -s --max-time 10 https://ifconfig.me || curl -4 -s --max-time 10 https://api.ipify.org)}"
PRIVATE_IP="$(hostname -I | awk '{print $1}')"
TURN_USERNAME="${TURN_USERNAME:-thooku}"
TURN_PASSWORD="${TURN_PASSWORD:-$(openssl rand -base64 18)}"
REALM="thookumadurai"

if [[ -z "$PUBLIC_IP" || -z "$PRIVATE_IP" ]]; then
  echo "ERROR: could not detect IPs. Set PUBLIC_IP/PRIVATE_IP env vars and re-run."
  exit 1
fi

# 1) Fill public/private IP into coturn.conf
sed -i "s|__PUBLIC_IP__|$PUBLIC_IP|g; s|__PRIVATE_IP__|$PRIVATE_IP|g" coturn/coturn.conf
echo "external-ip set to $PUBLIC_IP/$PRIVATE_IP"

# 2) Generate the userdb key and write turnuserdb.conf
KEY="$(docker run --rm coturn/coturn:latest turnadmin -k -u "$TURN_USERNAME" -r "$REALM" -p "$TURN_PASSWORD")"
KEY="${KEY#0x}"   # drop the 0x prefix if present (we re-add it below)
printf '# Generated by setup.sh on the VPS - do not commit\n%s:0x%s:%s\n' "$TURN_USERNAME" "$KEY" "$REALM" > coturn/turnuserdb.conf
echo "turnuserdb.conf written"

# 3) Start the server
docker compose -f docker-compose.turn.yml up -d

# 4) Show what to paste into Render
cat <<EOF

=== TURN SERVER RUNNING on $PUBLIC_IP:3478 ===

Paste these into Render -> backend -> Environment (then redeploy):

  TURN_SERVER_URL=turn:$PUBLIC_IP:3478?transport=udp
  TURN_SERVER_USERNAME=$TURN_USERNAME
  TURN_SERVER_CREDENTIAL=$TURN_PASSWORD

Test after redeploy: open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
and use those same three values - "relay" candidates must show.

WARNING: the password above is shown only once. Store it now.
EOF
